### ISSUE TITLE
Import-Module Pansies fails

### ISSUE THREAD

**Issue by kort3x** [PoshCode/Pansies#11]
When I try to import Pansies i get:

```
Import-Module : Ein Teil des Pfades "C:\Program Files\WindowsPowerShell\Modules\UserProfile\1.0\UserProfile.Format.ps1xml" konnte
nicht gefunden werden.
In Zeile:1 Zeichen:1
+ Import-Module Pansies
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:String) [Import-Module], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

roughly translates to:
```
Part of the path "C: \ Program Files \ WindowsPowerShell \ Modules \ UserProfile \ 1.0 \ UserProfile.Format.ps1xml" failed to be found.
```

I checked and well there is directory UserProfile in the Modules folder.
When should this directory and the file get created?
What can I do to fix this?

> PSVersion                      5.1.17134.81
> PSEdition                      Desktop
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
> BuildVersion                   10.0.17134.81
> CLRVersion                     4.0.30319.42000
> WSManStackVersion              3.0
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1

**Comment by Jaykul** [comment]
I really have no idea what this is about. I assume you had a format file from there imported, but that it was missing when you imported Pansies, and PowerShell is complaining because Pansies includes it's own format file, and PowerShell may therefore be trying to update all the format files...

Can't see how it's caused by Pansies though. 

- Which version of Pansies was it? 
- Can you try the latest pre-release?

```posh
Update-Module Pansies -AllowPrerelease
```
