### ISSUE TITLE
bug with Powershell 7.0.2 and 3

### ISSUE THREAD

**Issue by JM2K69** [PoshCode/Pansies#15]
# Unable to find type [PoshCode.Pansies.Console.WindowsHelper].
![image](https://user-images.githubusercontent.com/17923944/88049431-7099ae80-cb55-11ea-8f33-51341d1392dc.png)

Do you have a solution ?

**Comment by Jaykul** [comment]
Ooof! I totally forgot PowerLine was using that. You should not need that on modern Windows 10. Turn off the option in PowerLine:

```PowerShell
Set-PowerLinePrompt -RestoreVirtualTerminal:$false
```

I'll have to think about that. I removed all of the Windows-specific stuff when I finally released 1.3 because I decided that PANSIES needed to be strictly cross-platform, and the Windows-specific features could go in their own module if we needed them. I guess this might be the only actual use of one of them...

For what it's worth, the function it's looking for was just moved to `PoshCode.Pansies.NativeMethods`, there's a fix coming to PowerLine for that, it's tracked in Jaykul/PowerLine#64
