### ISSUE TITLE
Initializing Write-Host fails?

### ISSUE THREAD

**Issue by LukasMarsch** [PoshCode/Pansies#27]
When i load up a new Console and try to
```Powershell
Write-Host ">" -ForegroundColor "#222222" -BackgroundColor Gold
```
I get an Error
```Powershell
Write-Host: Cannot bind parameter 'BackgroundColor'. Cannot convert value "Gold" to type "System.ConsoleColor". Error: "Unable to match the identifier name Gold to a valid enumerator name. Specify one of the following enumerator names and try again:
Black, DarkBlue, DarkGreen, DarkCyan, DarkRed, DarkMagenta, DarkYellow, Gray, DarkGray, Blue, Green, Cyan, Red, Magenta, Yellow, White"
```

This is from the Legacy Write-Host command.
Once i call for example
```Powershell
Get-ColorWheel
```
I can run my first Write-Host command as expected

Terminal: Alacritty

Example:
![image](https://github.com/PoshCode/Pansies/assets/50878285/737be4e8-1a25-42eb-93d1-925fe97aa683)

**Comment by kilasuit** [comment]
Once you run Get-ColorWheel, Pansies will load and this replaces the default Write-Host with it's implementation
If you want this all the time, then load Pansies in your Profile then all calls to write-host will use the Pansies version in that session

Hope that helps @LukasMarsch!

**Comment by Jaykul** [comment]
You can call `PANSIES\Write-Host` explicitly -- otherwise, it only clobbers the built-in Write-Host when you have Pansies imported.

You can import it in your profile, locally, that takes care of everything.

In scripts, you should `#requires -module Pansies` 

In modules, you should add it to your module manifest in `RequiredModules = @('Pansies')`
